[app]
port = ":8081"
session_secret = "dev_session_secret"
jwt_secret = "dev_jwt_secret"
baseurl = "/cms"
domain = "localhost"

[db]
user = "root"
password = "123456"
host = "127.0.0.1"
name = "cms"
port = "3306"

[license]
path = "C:\\truck\\deplay\\backend\\license.json"
secret = "YOUR_SECRET"
