[app]
port = ":8081"
session_secret = "dev_session_secret"
jwt_secret = "dev_jwt_secret"
baseurl = "/cms"
domain = "localhost"

[db]
user = "root"
password = "123456"
host = "localhost"
name = "cms"
port = "3306"

[license]
path = "license.json"
secret = "dev_license_secret"
